/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ibaixin_chat_util_NativeUtil */

#ifndef _Included_net_ibaixin_chat_util_NativeUtil
#define _Included_net_ibaixin_chat_util_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ibaixin_chat_util_NativeUtil
 * Method:    listFileNames
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_ibaixin_chat_util_NativeUtil_listFileNames
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
